//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystemApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbglTicket
    {
        public int Id { get; set; }
        public string TicketID { get; set; }
        public string WebURL { get; set; }
        public string KeyDataPoints { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public string Keywords { get; set; }
        public string MetaDescription { get; set; }
    }
}
